buildscript {
    ext.kotlin_version = '1.8.0'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:7.4.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
    
    // Переопределяем Kotlin для всех подпроектов, включая плагины
    project.plugins.withId('kotlin-android') {
        project.kotlin.kotlinDependencyHandler.api "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    }
    
    // Принудительно задаем версию всех зависимостей Kotlin
    configurations.all {
        resolutionStrategy.eachDependency { DependencyResolveDetails details ->
            if (details.requested.group == 'org.jetbrains.kotlin') {
                details.useVersion kotlin_version
            }
        }
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
    
    // Изменяем настройки подпроектов
    afterEvaluate {
        if (project.hasProperty('android')) {
            android {
                compileSdkVersion 34
                
                compileOptions {
                    sourceCompatibility JavaVersion.VERSION_1_8
                    targetCompatibility JavaVersion.VERSION_1_8
                }
            }
        }
    }
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}